change unzip tool

diff --git a/.github/workflows/analyze_data.yml b/.github/workflows/analyze_data.yml
--- a/.github/workflows/analyze_data.yml
+++ b/.github/workflows/analyze_data.yml
@@ -110,14 +110,12 @@ jobs:
           fi
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Install 7-Zip
+        run: sudo apt-get update && sudo apt-get install -y p7zip-full
         
       - name: Extract zip files into folders with cleaned base name
         run: |
-          sudo rm -rf /usr/share/dotnet
-          sudo rm -rf /opt/ghc
-          sudo rm -rf "/usr/local/share/boost"
-          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
-
 
           # Navigate to the directory containing the zip files
           cd ./projects/reports
@@ -142,21 +140,21 @@ jobs:
 
           # # Extract zip files into folders with the same name
           for f in *.zip; do
-              folder_name="${f%.*}"
-              echo "Folder name: $folder_name"
-              # Attempt to unzip the file into the specified folder
-              if ! unzip -o -d "$folder_name" "$f" 2>&1 | tee unzip_log.txt; then
-                  # If unzip fails, print error message from log
-                  echo "Error unzipping $f"
-                  cat unzip_log.txt
-                  exit 1  # Exit the script with an error status
-              else
-                  echo "Unzip finished: $folder_name"
-                  # Optionally, you can remove the log file after successful unzip
-                  rm unzip_log.txt
-              fi
-              # Delete the zip file after extracting
-              rm "$f"
+            folder_name="${f%.*}"
+            echo "Folder name: $folder_name"
+            # Use 7za to extract the zip file
+            if ! 7za x "$f" -o"$folder_name" > 7za_output.log 2>&1; then
+                echo "Error extracting $f - see 7za_output.log for details"
+                cat 7za_output.log
+                exit 1  # Exit the script with an error status
+            else
+                echo "Extraction finished: $folder_name"
+                # Optionally, remove the log file after successful extraction
+                rm 7za_output.log
+            fi
+            # Delete the zip file after extracting
+            echo "Removing zip file: $f"
+            rm "$f"
           done
 
           # Within each folder, rename the file db.pymon to db.pymon_ext
