better error handling

diff --git a/.github/workflows/analyze_data.yml b/.github/workflows/analyze_data.yml
--- a/.github/workflows/analyze_data.yml
+++ b/.github/workflows/analyze_data.yml
@@ -30,43 +30,45 @@ jobs:
             
           - name: Download files from multiple releases
             run: |
-                # Array containing the alphabet and numbers for iterating
-                chars=( {a..z} {0..9} )
+              # Array containing the alphabet and numbers for iterating
+              chars=( {a..z} {0..9} )
 
-                # Loop through each repository provided in the GitHub Action input
-                for repo in ${{ github.event.inputs.repositories }}; do
-                  echo "Downloading from $repo"
+              # Loop through each repository provided in the GitHub Action input
+              for repo in ${{ github.event.inputs.repositories }}; do
+                echo "Downloading from $repo"
+                
+                # Loop through each character in the array
+                for char in "${chars[@]}"; do
+                  echo "Attempting to download files starting with $char from $repo"
                   
-                  # Loop through each character in the array
-                  for char in "${chars[@]}"; do
-                    echo "Attempting to download files starting with $char from $repo"
+                  # Flag to control the retry mechanism
+                  retry_needed=true
+                  while [ "$retry_needed" = true ]; do
+                    # Attempt to download files and capture both stdout and stderr to check for errors
+                    output=$(gh release download ${{ github.event.inputs.release-tag }} -R $repo -D ./projects/reports --clobber --pattern "$char*" 2>&1)
                     
-                    # Flag to control the retry mechanism
-                    retry_needed=true
-                    while [ "$retry_needed" = true ]; do
-                      # Attempt to download files and capture stderr to check for rate limit error
-                      error_message=$(gh release download ${{ github.event.inputs.release-tag }} -R $repo -D ./projects/reports --clobber --pattern "$char*" 2>&1 > /dev/null)
-                      
-                      if [[ "$error_message" == *"HTTP 403: API rate limit exceeded for site ID installation"* ]]; then
-                        echo "Rate limit exceeded, waiting 30 seconds before retrying..."
-                        sleep 30
+                    if [[ "$output" == *"HTTP 403: API rate limit exceeded for site ID installation"* ]]; then
+                      echo "Rate limit exceeded, waiting 30 seconds before retrying..."
+                      sleep 30
+                    else
+                      retry_needed=false
+                      # Check if the command exited with an error
+                      if [[ $? -ne 0 ]]; then
+                        echo "Failed to download files starting with $char from $repo. Error: $output" >> download_failures.log
                       else
-                        retry_needed=false
-                        if [[ -n "$error_message" ]]; then
-                          echo "Failed to download files starting with $char from $repo. Error: $error_message" >> download_failures.log
-                        else
-                          echo "Download successful for files starting with $char from $repo"
-                        fi
+                        echo "Download successful for files starting with $char from $repo"
                       fi
-                    done
+                    fi
                   done
                 done
+              done
 
-                # Counting the number of zip files in the output directory
-                zip_count=$(find ./projects/reports -type f -name '*.zip' | wc -l)
+              # Counting the number of zip files in the output directory
+              zip_count=$(find ./projects/reports -type f -name '*.zip' | wc -l)
 
-                echo "Download process completed. Check download_failures.log for any issues."
-                echo "Total number of .zip files downloaded: $zip_count"
+              echo "Download process completed. Check download_failures.log for any issues."
+              echo "Total number of .zip files downloaded: $zip_count"
+
             env:
               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           
